### ISSUE TITLE
how add LIKE & subscribe

### ISSUE THREAD

**Issue by Ondrik8** [tegal1337/Youtube-Auto-Commenter#12]
hello very cool project)!
please tell me how to like and subscribe to the channel?

**Comment by fdciabdul** [comment]
if you see the old commit from me , you will see the function to subscribe my channel

https://github.com/tegal1337/Youtube-Auto-Commenter/commit/95fc014b3dca1cda29e660447cc2fe957aa0c5b2#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aL43

you can implement this one for another channel
