### ISSUE TITLE
Configurable random comment text

### ISSUE THREAD

**Issue by mrnams** [tegal1337/Youtube-Auto-Commenter#2]
Can you please allow user to add array of comment texts in config file, and randomly select string from that array and comment it.

**Comment by fdciabdul** [comment]
ok

**Comment by samruddhinw** [comment]
@fdciabdul I dont see updated files? Did you forget to push changes?

**Comment by mrnams** [comment]
@fdciabdul no file updated, did you forget to push changes?

**Comment by fdciabdul** [comment]
i was update this one tho

**Comment by fdciabdul** [comment]
thanks for your patience xD
