### ISSUE TITLE
not starting chrome even installed

### ISSUE THREAD

**Issue by amandalal123** [tegal1337/Youtube-Auto-Commenter#7]
┌──(sad㉿Demon)-[~/Downloads/Youtube-Auto-Commenter]
└─$ node main.js
(node:29836) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/sad/Downloads/Youtube-Auto-Commenter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/home/sad/Downloads/Youtube-Auto-Commenter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:29836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
                                                                                                                
┌──(sad㉿Demon)-[~/Downloads/Youtube-Auto-Commenter]
└─$

**Comment by MinSteRexS** [comment]
yeah, its seem cannot be run... 
what i can do next ? 

![image](https://user-images.githubusercontent.com/103582194/163316188-d451af9c-4d81-424c-9d8f-c52a05847e68.png)

**Comment by fdciabdul** [comment]
> ┌──(sad㉿Demon)-[~/Downloads/Youtube-Auto-Commenter] └─$ node main.js (node:29836) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT
> 
> TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> 
> ```
> at onClose (/home/sad/Downloads/Youtube-Auto-Commenter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
> at ChildProcess.<anonymous> (/home/sad/Downloads/Youtube-Auto-Commenter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
> at ChildProcess.emit (events.js:400:28)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
> at onErrorNT (internal/child_process.js:469:16)
> at processTicksAndRejections (internal/process/task_queues.js:82:21)
> ```
> 
> (Use `node --trace-warnings ...` to show where the warning was created) (node:29836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:29836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> ┌──(sad㉿Demon)-[~/Downloads/Youtube-Auto-Commenter] └─$

delete this line https://github.com/tegal1337/Youtube-Auto-Commenter/blob/795abe272344ea981d4d4c30b18785f4a0288eec/main.js#L31

**Comment by amandalal123** [comment]
thanks it worked

> > ┌──(sad㉿Demon)-[~/Downloads/Youtube-Auto-Commenter] └─$ node main.js (node:29836) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! spawn C:\Program Files\Google\Chrome\Application\chrome.exe ENOENT
> > TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
> > ```
> > at onClose (/home/sad/Downloads/Youtube-Auto-Commenter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
> > at ChildProcess.<anonymous> (/home/sad/Downloads/Youtube-Auto-Commenter/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
> > at ChildProcess.emit (events.js:400:28)
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
> > at onErrorNT (internal/child_process.js:469:16)
> > at processTicksAndRejections (internal/process/task_queues.js:82:21)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (Use `node --trace-warnings ...` to show where the warning was created) (node:29836) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:29836) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> > ┌──(sad㉿Demon)-[~/Downloads/Youtube-Auto-Commenter] └─$
> 
> delete this line
> 
> https://github.com/tegal1337/Youtube-Auto-Commenter/blob/795abe272344ea981d4d4c30b18785f4a0288eec/main.js#L31

thanks it worked

**Comment by i6c** [comment]
bruh 😐😐😐
