### ISSUE TITLE
Captcha ruins everything 

### ISSUE THREAD

**Issue by i6c** [tegal1337/Youtube-Auto-Commenter#8]
I made a selector  that checks for captcha and will just terminate the process if found. I can make a pr if you want with this , but it always  trys to enter the password in the captcha box without my update.

**Comment by fdciabdul** [comment]
captcha ?

**Comment by fdciabdul** [comment]
you means two FA ?

**Comment by i6c** [comment]
no  i mean captcha. upon signing on  i get a captcha almost everytime  i have to wait a while before  trying again its RNG for me. am running this in chromium

**Comment by i6c** [comment]
also  it never stays signed in the browser

**Comment by fdciabdul** [comment]
> also it never stays signed in the browser

https://github.com/tegal1337/Youtube-Auto-Commenter/blob/795abe272344ea981d4d4c30b18785f4a0288eec/main.js#L52

uncomment this line
